### ISSUE TITLE
How can i set Parameters ?

### ISSUE THREAD

**Issue by malcomxcia** [hgross/node-red-contrib-tuya-smart#4] opened 2019-02-12 18:07 UTC
Hello ! Nice Work ;)

But how can I turn a lamp or an Socket on or off ?

I tried with an Inject Node like this 

> {"set":false}

 but doesn't works .....

Where is my mistake ?

Greets and have an Nice Day
Malcom

**Comment by hgross** [comment] 2019-02-12 19:32
Hi, try to inject `{"set": false, "dpsIndex": 1}` for off; `{"set": true, "dpsIndex": 1}` for on.
Make sure the deviceId and deviceKey are correct.

**Comment by malcomxcia** [comment] 2019-02-12 19:37
Thank you for your Answer ;)

I also tested that `{"set": false, "dpsIndex": 1}` but also doesn't work

My Device is connected

![screenshot-192 168 0 79-1880-2019 02 12-20-39-56](https://user-images.githubusercontent.com/17162789/52663222-6d34d900-2f06-11e9-9a76-e18e69f08b0d.jpg)

![screenshot-192 168 0 79-1880-2019 02 12-20-43-53](https://user-images.githubusercontent.com/17162789/52663376-cc92e900-2f06-11e9-97e0-c9128d8d168a.jpg)

**Comment by jhortolano** [comment] 2019-02-20 17:25
Hi, I also have the same issue, I can connect to the device (a smart plug in this case) but can't turn on or off from node-red.
I'm also trying independently: {"set": false, "dpsIndex": 1} / {"set": true, "dpsIndex": 1} / {"set": false, "dpsIndex": 101} / {"set": true, "dpsIndex": 101}

Any help is much appreciated.
Thanks!

**Comment by hgross** [comment] 2019-02-21 23:47
The input looks correct to me - do you see the correct (output) status of the node in the debug log? 
Something like this?  ![tuya 3-socket powerstrip outputs explained](https://raw.githubusercontent.com/hgross/node-red-contrib-tuya-smart/master/images/output-power-strip.png "tuya 3-socket powerstrip outputs explained")

(Instead of answers described in this issue: https://github.com/hgross/node-red-contrib-tuya-smart/issues/3 )

**Comment by mariley2250** [comment] 2019-02-27 23:05
Hi,

I have the same issue. I am currently seeing the correct output and the status changes if i manual operate the switch. It just seems that the input of the block is not being recognised.

Any help would be appreciated. 

Thanks

**Comment by jhortolano** [comment] 2019-02-27 23:13
Hi,

I haven't tried in node-red after finding this out, will do it when I get a chance, but I think the problem is not related to this plugin, but the local_key. **Every time you reset the plug** (or bulb) in the android app (or iOS, I guess), **the local key is reset**, and you need to get it and set it whereever you want to use the plug.
I'd recommend to use the python library or node to test it, and then use it in node red.

As I said, I haven't tested in node red yet, but it was showing connected even when the local key was wrong, I would need to test it with the right key.

**Comment by mariley2250** [comment] 2019-02-27 23:58
I used wireshark to get the setting for the switch (as below).
When you say local key are you meaning the deviceid?? 

![image](https://user-images.githubusercontent.com/13849294/53531582-9e88e800-3b47-11e9-9d76-056939702abb.png)

**Comment by hgross** [comment] 2019-02-28 13:43
@jhortolano meant the deviceKey and the proposed debug method is very helpful. 
You can use https://github.com/TuyaAPI/cli to test your tuya device from the console independent from NodeRED:
like this `tuya-cli get --id 20075335840d8e902ee0 --key 0a47abaf0ebf04a1 --ip 192.168.15.121`

If you can see correct ouptut for the device state in NodeRED, there might be a problem with the node. 
Are you sure, you are using the latest version from npm (1.1.0)?
There was a [breaking change in 1.1.0 regarding input format](https://github.com/hgross/node-red-contrib-tuya-smart/blob/master/CHANGELOG.md) - is it possible that you are on an older version?

**Comment by jhortolano** [comment] 2019-02-28 13:47
@mariley2250 For the device key (or local key), I got it using the following method:
https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md

**Comment by mariley2250** [comment] 2019-02-28 22:38
Hi @hgross,

Tried to run script external to node-red with the following results.
![image](https://user-images.githubusercontent.com/13849294/53603437-a27b3f80-3c05-11e9-9e86-0899e29b8c1e.png)

I used the method @jhortolano to get an updated key which rendered the following results
![light switch key](https://user-images.githubusercontent.com/13849294/53603481-c2126800-3c05-11e9-82c4-d9f4a2f40cd7.PNG)

**Comment by hgross** [comment] 2019-02-28 23:09
Looks like tuya-cli is broken because you have installed the 4.0.0 version of tuyapi released by @codetheweb some days ago.
This line https://github.com/codetheweb/tuyapi/blob/master/index.js#L266 and the introduced breaking changes with v4 (https://github.com/codetheweb/tuyapi/releases/tag/v4.0.0) lead to my assumption.

This could also cause your problem with setting the state - but then you wouldn't be able to get the status either. 
I will have a look at the 4.x versions.

In the meantime `npm install -g codetheweb/tuyapi@3.2.3` might help you out.

**Comment by codetheweb** [comment] 2019-02-28 23:12
Thanks for tagging me @hgross, forgot to update the CLI.  I'll get to it right now.

**Comment by codetheweb** [comment] 2019-02-28 23:21
Should be fixed now @hgross @mariley2250.  Update with `npm i @tuyapi/cli -g` and let me know if it works.

**Comment by stepic** [comment] 2019-03-03 13:57
I have the same issue. Any news?
deviceId and deviceKey tested with tuya-cli

Thanks!

**Comment by hgross** [comment] 2019-03-03 14:22
Couldn't reproduce it with my devices (a 3-socket-powerstrip from hyleton, multiple single-socket devices from gosund) locally. I published a new version using the latest 3.x version of Tuyapi. What smart-devices (and from which vendors) are you using? Do you see anything in the logs (NodeRED as well as console-log of the browser)?

**Comment by stepic** [comment] 2019-03-03 15:49
I have Houzetek AWP07L Smart WiFi Plug. Power status is being reported correctly, but I cannot switch power status (injecting with an inject node: json {"set": true}). The same action with tuya-cli works.

**Comment by hgross** [comment] 2019-03-03 19:13
Ok, that is odd. 

Can you please try, if injecting `{"set": true, "dpsIndex": 1}` does the trick? 
Also, what is the actual json output? (please attach)
How are you starting node-red - can you see and share the output from the commandline?

**Comment by stepic** [comment] 2019-03-03 19:44
No luck also adding dpsIndex.

This is msg.payload output:
object
data: object
devId: "xxxxxxxxxxxxxx"
dps: object
1: false
2: 0
4: 0
5: 0
6: 2317
deviceIp: "192.168.1.163"
deviceId: "xxxxxxxx"
deviceName: "piantana"

node-red is being started with systemctl (user pi) and I don't see any particular message on console

**Comment by garynl** [comment] 2019-03-03 20:18
dpsIndex - capital 'I'. Its case sensitive

**Comment by stepic** [comment] 2019-03-03 20:27
Solved, it was my fault setting inject node, sorry

**Closed as completed** 2019-03-07 21:42 UTC

**Comment by Sukuri** [comment] 2019-10-25 05:46
hi @hgross , I've filled in the parameter but not connected, can I know what's the problem pelase?
![image](https://user-images.githubusercontent.com/33746905/67546009-b5f78f80-f72d-11e9-880a-8894b7dfc5f5.png)
![image](https://user-images.githubusercontent.com/33746905/67546071-e17a7a00-f72d-11e9-85fb-c2b0bbe64976.png)

**Comment by Sukuri** [comment] 2019-10-25 05:49
hi @hgross , I've set up the parameters but disconnected, can I know what's the problem please?
![image](https://user-images.githubusercontent.com/33746905/67546141-1dadda80-f72e-11e9-8bf4-879727cde3ae.png)
![image](https://user-images.githubusercontent.com/33746905/67546157-2acac980-f72e-11e9-9f7f-77720451bfce.png)

**Comment by Sukuri** [comment] 2019-10-25 06:44
can help please @malcomxcia @stepic @hgross @jhortolano @codetheweb

**Comment by codetheweb** [comment] 2019-10-26 02:03
It's hard to say @Sukuri but going by the device name it appears to be a sensor.  Most sensors are not supported by TuyAPI at this time due to the fact they are not constantly connected to WiFi (they only connect for a short period to send updates).

**Comment by Sukuri** [comment] 2019-10-26 02:39
@codetheweb noted and thanks for the reply

**Comment by abbasaabbas** [comment] 2020-03-15 12:15
> Hi @hgross,
> 
> Tried to run script external to node-red with the following results.
> ![image](https://user-images.githubusercontent.com/13849294/53603437-a27b3f80-3c05-11e9-9e86-0899e29b8c1e.png)
> 
> I used the method @jhortolano to get an updated key which rendered the following results
> ![light switch key](https://user-images.githubusercontent.com/13849294/53603481-c2126800-3c05-11e9-82c4-d9f4a2f40cd7.PNG)

Hi, 
I have Zoozee smart plug  but I don't find the device Key, have you an idea how to get it? 
Thank you

**Comment by abbasaabbas** [comment] 2020-03-15 12:36
Hi,
I have Zoozee smart plug but I don't find the device Key, have you an idea how to get it?
Thank you

**Comment by sam1am** [comment] 2020-10-11 05:37
Boy I wish there were an easier way to do this.
